// Package migrations embeds the canonical schema.
//
// SQL is kept explicit and reviewable rather than generated by an ORM, because the
// temporal and index behavior of these tables is the product (AGENTS.md section 34).
package migrations

import "embed"

// FS holds every migration file, applied in filename order by
// internal/store/ledger. Migrations are append-only: an applied file is never
// edited, since the runner verifies checksums.
//
//go:embed *.sql
var FS embed.FS
